source "https://rubygems.org"

ruby ">= 3.4.0", "< 3.5.0"

gem "rails", "~> 8.1.3"
gem "bcrypt", "~> 3.1"
gem "jwt", "~> 3.1"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
